name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-gha-yaml:
    name: GitHub Actions YAML Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.27.0

      - name: aqua install
        run: aqua install

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint/Format
        run: npm run check

      - name: Test
        run: npm run test

      - name: Packaging
        run: npm run package

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          org_name: ${{ github.repository_owner }}

      - name: Print Output
        id: output
        run: echo "${{ toJson(steps.test-action.outputs) }}"
